trigger:
- main

pool: "Default"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

# Chạy các bài kiểm tra cho cả API và MVC
- task: DotNetCoreCLI@2
  displayName: 'Run Tests for API and MVC'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
  continueOnError: false  # Dừng nếu có lỗi

# Xây dựng dự án API
- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: 'build'
    projects: '**/API.csproj'  # Thay thế bằng đường dẫn đến project API của bạn
    arguments: '--configuration $(buildConfiguration)'

# Xuất bản API
- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    projects: '**/API.csproj'  # Thay thế bằng đường dẫn đến project API của bạn
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'

# Xây dựng dự án MVC
- task: DotNetCoreCLI@2
  displayName: 'Build MVC'
  inputs:
    command: 'build'
    projects: '**/MVC.csproj'  
    arguments: '--configuration $(buildConfiguration)'

# Xuất bản MVC
- task: DotNetCoreCLI@2
  displayName: 'Publish MVC'
  inputs:
    command: 'publish'
    projects: '**/MVC.csproj'  # Thay thế bằng đường dẫn đến project MVC của bạn
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/mvc'

# Xuất bản artefacts đã build
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
