trigger:
- main

pool: "Default"

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  apiProject: 'D:\FPT\chuyennghanh8\prn231\code\Project-PRN231\API\API.csproj'  # Đường dẫn đến dự án API
  mvcProject: 'D:\FPT\chuyennghanh8\prn231\code\Project-PRN231\MVC\MVC.csproj'  # Đường dẫn đến dự án MVC

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# Phục hồi NuGet cho API và MVC
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages for API'
  inputs:
    command: 'restore'
    projects: '$(apiProject)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages for MVC'
  inputs:
    command: 'restore'
    projects: '$(mvcProject)'

# Chạy kiểm tra cho API
- task: DotNetCoreCLI@2
  displayName: 'Run Tests for API'
  inputs:
    command: 'test'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration)'
  continueOnError: false  # Dừng nếu có lỗi

# Chạy kiểm tra cho MVC
- task: DotNetCoreCLI@2
  displayName: 'Run Tests for MVC'
  inputs:
    command: 'test'
    projects: '$(mvcProject)'
    arguments: '--configuration $(buildConfiguration)'
  continueOnError: false  # Dừng nếu có lỗi

# Xây dựng API
- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: 'build'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration)'

# Xây dựng MVC
- task: DotNetCoreCLI@2
  displayName: 'Build MVC'
  inputs:
    command: 'build'
    projects: '$(mvcProject)'
    arguments: '--configuration $(buildConfiguration)'

# Xuất bản API
- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\api'

# Xuất bản MVC
- task: DotNetCoreCLI@2
  displayName: 'Publish MVC'
  inputs:
    command: 'publish'
    projects: '$(mvcProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\mvc'

# Xuất bản artefacts đã build
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
