trigger:
- main

pool: "Default"

variables:
  solution: '**/*.sln'  # Tìm kiếm tất cả các tệp .sln trong thư mục
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Sử dụng SDK .NET 8
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'  # Khôi phục gói NuGet cho tất cả các dự án
    
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '$(solution)'  # Chạy bài kiểm tra cho tất cả các dự án
    arguments: '--configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'  # Xây dựng tất cả các dự án
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish Solution'
  inputs:
    command: 'publish'
    projects: '$(solution)'  # Xuất bản tất cả các dự án
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Đường dẫn đến thư mục chứa các artefact đã xuất bản
    ArtifactName: 'drop'  # Tên artefact
    publishLocation: 'Container'  # Vị trí xuất bản
