trigger:
- main

pool: 'Default'  # Sử dụng máy ảo Windows mới nhất để build

variables:
  solution: '**/*.sln'  # Chỉ định file solution cần build
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Step 1: Cài đặt .NET SDK 8.0 (nếu chưa có)
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x.x'  # Sử dụng phiên bản .NET 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Step 2: Restore NuGet packages sử dụng .NET CLI
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'  # Chỉ định solution để restore

# Step 3: Build solution bằng .NET CLI
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# Step 4: Chạy Unit Tests (nếu có) bằng .NET CLI
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'

# Step 5: Publish artifact để lưu trữ sau khi build thành công
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
